default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exotic_euro_development

test:
  <<: *default
  database: exotic_euro_test

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
