production:
  connects_to:
    writing: primary
    reading: primary
    cache: cache
    queue: queue
    cable: cable

  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

  cache:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cable_migrate
