default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

production:
  primary:
    <<: *default

  cable:
    <<: *default
    migrations_paths: db/cable_migrate

  queue:
    <<: *default
    migrations_paths: db/queue_migrate

  cache:
    <<: *default
    migrations_paths: db/cache_migrate
